app:
  name: test
  language: zh-CN
  supportLanguages:
    - zh-CN
    - en-US
  env: DEV
  host: 127.0.0.1
  port: 8080

page-web:
  theme: cerulean

database:
  url: jdbc:mysql://localhost:3306/main?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: root
  createTableEnabled: true
  showSQLEnabled: true

email:
  url: http://localhost

web:
  cacheEnabled: false
  roots:
    - ./jweb-framework/admin/src/main/dist/web
    - ./jweb-framework/web/src/main/web
    - ./jweb-cms/jweb-email/email-admin/src/main/dist/web
    - ./jweb-cms/user-admin/src/main/dist/web
    - ./jweb-cms/user-web/src/main/web
    - ./jweb-cms/captcha-web-simple/src/main/web
    - ./jweb-cms/pincode-web/src/main/web
    - ./jweb-cms/file-admin/src/main/dist/web
    - ./jweb-cms/page-web/src/main/web
    - ./jweb-cms/page-admin/src/main/dist/web
    - ./jweb-cms/comment-admin/src/main/dist/web
    - ./jweb-cms/comment-web/src/main/web
    - ./jweb-main/src/main/resources/web

user:
  defaultAdminUser:
    username: admin
    password: admin